### ISSUE TITLE
erro on "Select Dangling Edges" 

### ISSUE THREAD

**Issue by lucasmation** [strk/qgis_pgis_topoedit#4]
Upon experimenting with this package, I tryed the "Select Dangling Edges" function on a topology (created recently with Postgis 2.2.1) and got the error bellow?

An error has occured while executing Python code:

Traceback (most recent call last):
  File "/home/DLIPEA/r342471958/.qgis2/python/plugins/pgtopoeditor/pgtopoeditor.py", line 116, in doSelDanglingEdges
    having count(e.edge_id) = 1''')
ProgrammingError: relation "side_spikes.node" does not exist
LINE 3: from "topo_bahia2".edge_data e, side_spikes.node n
                                        ^

Python version:
2.7.3 (default, Jun 22 2015, 19:44:33) 
[GCC 4.6.3]

QGIS version:
2.8.2-Wien Wien, exported

Python path: ['/usr/share/qgis/python/plugins/processing', '/usr/share/qgis/python', u'/home/DLIPEA/r342471958/.qgis2/python', u'/home/DLIPEA/r342471958/.qgis2/python/plugins', '/usr/share/qgis/python/plugins', '/usr/lib/python2.7', '/usr/lib/python2.7/plat-linux2', '/usr/lib/python2.7/lib-tk', '/usr/lib/python2.7/lib-old', '/usr/lib/python2.7/lib-dynload', '/usr/local/lib/python2.7/dist-packages', '/usr/lib/python2.7/dist-packages', '/usr/lib/python2.7/dist-packages/PIL', '/usr/lib/python2.7/dist-packages/gst-0.10', '/usr/lib/python2.7/dist-packages/gtk-2.0', '/usr/lib/pymodules/python2.7', '/usr/lib/python2.7/dist-packages/ubuntu-sso-client', '/usr/lib/python2.7/dist-packages/ubuntuone-client', '/usr/lib/python2.7/dist-packages/ubuntuone-control-panel', '/usr/lib/python2.7/dist-packages/ubuntuone-couch', '/usr/lib/python2.7/dist-packages/ubuntuone-installer', '/usr/lib/python2.7/dist-packages/ubuntuone-storage-protocol', '/usr/lib/python2.7/dist-packages/wx-2.8-gtk2-unicode', u'/home/DLIPEA/r342471958/.qgis2//python', '/usr/share/qgis/python/plugins/fTools/tools']

**Comment by strk** [comment]
Oops, good catch !
Are you in a position to test 12a06f77de59c58e0ab01bde6fff2c0ae5e96e37 before I publish the fix ?

**Comment by strk** [comment]
Actually, I've published 0.2.2, trusting my fingers (shouldn't be done, I know).
Can you please let me know if my trust was too badly posed ?

**Comment by lucasmation** [comment]
It works on a different computer (windows server, qgis 2.8.1). (the Linux one crashed now, I'll test later)

**Comment by lucasmation** [comment]
What does this function do in the background?

It is funny, in my tests, , if find 160 "dangling edges". Some of them are polygons (As) that were completelly inside other polygons (Bs). In other case the dangling edge seems to be part of a longer edge.

**Comment by lucasmation** [comment]
I was using ST_SimplifyVW, as was suggested to us in this question: http://gis.stackexchange.com/questions/173977/how-to-remove-spikes-in-polygons-with-postgis

what is your take on this?

**Comment by strk** [comment]
On Mon, Jan 25, 2016 at 07:57:13AM -0800, lucasmation wrote:
> What does this function do in the background?

It selects edges that are not connected to another edge on at least
one end.

--strk;

**Comment by lucasmation** [comment]
Ok, doen´t that select incorrectly the polygons that are fully contained in other polygon? 
Lets say polygon A is fully contained in B. And B has an inner hole, in the A area, like a donuts. I suppose that edge (between a and B) does not connect with any other.

**Comment by strk** [comment]
On Mon, Jan 25, 2016 at 08:18:47AM -0800, lucasmation wrote:
> Ok, doen´t that select incorrectly the polygons that are fully contained in other polygon? 

It doesn't select polygons at all.
It selects _edges_

If you show a picture (ascii art is welcome) it may help
understanding.

**Comment by lucasmation** [comment]
Sorry, old polygon language creeps in. 
160 edges are selected by the tool out of the 74k in the state of Bahia. 
Look at these two: 

![Alt text](https://www.dropbox.com/s/npl10y5swi96u1i/example_donut_select_dangling_edges_tool.PNG?raw=1)

**Comment by strk** [comment]
I see, you mean 'closed edges'.
It's probably not something we want to consider "Dangling", indeed.
Could you please file a separate ticket for this ?

Even better, a pull request !

**Comment by lucasmation** [comment]
The update is working on linux as well. Thus I am closing the issue
