### ISSUE TITLE
"Select Dangling Edges" tool selects  closed edges (it should not)

### ISSUE THREAD

**Issue by lucasmation** [strk/qgis_pgis_topoedit#5]
The tool is selecting closed edges as if they were Dangling Edges
For example, it selects the two edges bellow:

![Alt text](https://www.dropbox.com/s/npl10y5swi96u1i/example_donut_select_dangling_edges_tool.PNG?raw=1)

(have no idea how to contribute actual code to fix this)

**Comment by strk** [comment]
Are you sure it's just a single closed edge ?
QGIS DBManager has a TopologyViewer that gives you nodes, labels for left/right face and next edges etc.

You might check a very minimal testcase, composed of a single closed edge (a triangle, 4 vertices, last=first) .

**Comment by lucasmation** [comment]
How about this for a test example

create table a_pol AS
SELECT ST_MakePolygon(
		ST_ExteriorRing(ST_Buffer(foo.line,10)),
	ARRAY[foo.line,
		ST_ExteriorRing(ST_Buffer(ST_MakePoint(20,20),1)) ]
	) as geom
FROM
	(SELECT ST_ExteriorRing(ST_Buffer(ST_MakePoint(10,10),10,10))
		As line )
		As foo
UNION
SELECT ST_MakePolygon(ST_ExteriorRing(ST_Buffer(ST_MakePoint(10,10),10,10) ) ) AS geom

SELECT topology.CreateTopology('a_pol_topo');
SELECT topology.addtopogeometrycolumn('a_pol_topo', 'public','a_pol','tg_geom','POLYGON');
UPDATE a_pol SET tg_geom = toTopoGeom(geom,'a_pol_topo', 1) ;
-- Query returned successfully: 2 rows affected, 224 ms execution time.
This looks like this


the tool ends up selecting the outer border of the larger face (the external perimeter) and the small circle, which is a hole, has no other polygons "filling it". 

I don't understand why the other circle is selected. 

The small circle I this is OK, should be selected. In a sense, it is not bad that some tool (although the name becomes misleading) asks the user to inspect holes in the topology. 

(I'll now investigate  the issue on my actual data)

**Comment by lucasmation** [comment]
This is what the selection looks like

![Alt text](https://www.dropbox.com/s/z9h090kkm3d9jpx/test_topology_edges_selected.PNG?raw=1)

**Comment by strk** [comment]
Can you please give QGIS DBManager a try, to show more info about
the topology ? It's easy: open DBManager, select your topology schema
go to the Schema menu and you'll find "Topology Viewer" or something
like that.

**Comment by lucasmation** [comment]
Following your suggestion I did: DBManager > Select the Topology > Select the edge table. Then on the top menu:  Schema > TopoViewer. This added all aspects of the topology to the view area. 

this is what the test topology looks like:

![Alt text](https://www.dropbox.com/s/c6cdbw4gdbzpx88/test_topology_View_topology.PNG?raw=1)

What should I look for? Are these symbols documented somewhere?

**Comment by lucasmation** [comment]
And this ia a view of the polygons in my actual data (that I reported in the beginning)

![Alt text](https://www.dropbox.com/s/uelhg5z4yzii643/original_topology_problems_ViewTopology.PNG?raw=1)

**Comment by strk** [comment]
It shows the central hole is made of 2 edges rather than one,
which explains why it is not selected.

Anyway, I don't think closed edges should be selected by the tool,
so the ticket bug is valid.

About documentation: no, it's supposed to be intuitive
(check the name of the layers within the groups)

**Comment by lucasmation** [comment]
I agree about keeping the ticket

Final side note on this: In constructiong the example, I did not mean for the central "hole" to be made of two edges. Infact, if you look at the query, I expected the borders (inter border of the large polygon, and outer border of the central polygons) to be exactly the same, and become the same edge. What could have happened?

**Comment by strk** [comment]
The double edge is a known issue:
https://trac.osgeo.org/postgis/ticket/2175

The line was probably added once as the hole and once as the outer
shell of the internal polygon (your testcase wasn't minimal enough :)
