### ISSUE TITLE
wrong parameter

### ISSUE THREAD

**Issue by torecki** [strk/qgis_pgis_topoedit#6]
I get an error message and the plugin does'nt work.

> Algorithmus Make valid startet...

> [Error 87] Falscher Parameter See log for more details

> "C:/Users/Torsten/.qgis2/python/plugins\processinglwgeomprovider\LwgeomAlgorithm.py", line 117, in > processAlgorithm
	>		    liblwgeom = self.getLwgeomLibrary()
	>		  File "C:/Users/Torsten/.qgis2/python/plugins\processinglwgeomprovider\LwgeomAlgorithm.py", line 97, in getLwgeomLibrary
		>	    lib = ctypes.CDLL(libpath)
		>	  File "E:\Programme\osgeo4w\apps\Python27\lib\ctypes\__init__.py", line 365, in __init__
		>	    self._handle = _dlopen(self._name, mode)
		>	WindowsError: [Error 87] Falscher Parameter
I tried on Windows 10 64 bit with QGIS 2.18.20

Thanks in advance

**Comment by strk** [comment]
> > "C:/Users/Torsten/.qgis2/python/plugins\processinglwgeomprovider\LwgeomAlgorithm.py", line 117, in > processAlgorithm
> 	>		    liblwgeom = self.getLwgeomLibrary()
> 	>		  File "C:/Users/Torsten/.qgis2/python/plugins\processinglwgeomprovider\LwgeomAlgorithm.py", line 97, in getLwgeomLibrary
> 		>	    lib = ctypes.CDLL(libpath)
> 		>	  File "E:\Programme\osgeo4w\apps\Python27\lib\ctypes\__init__.py", line 365, in __init__
> 		>	    self._handle = _dlopen(self._name, mode)
> 		>	WindowsError: [Error 87] Falscher Parameter
> I tried on Windows 10 64 bit with QGIS 2.18.20

The above error is NOT coming from this plugin.
Search for  "lwgeom provider qgis processing"

#close
